
classdef gripperPoseRequest < ros.Message
    %gripperPoseRequest MATLAB implementation of px_msgs/gripperPoseRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'px_msgs/gripperPoseRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '759b8154db4f147b06513af5ff44750b' % The MD5 Checksum of the message definition
        PropertyList = { 'DesiredGripperPose' } % List of non-constant message properties
        ROSPropertyList = { 'desiredGripperPose' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        DesiredGripperPose
    end
    methods
        function set.DesiredGripperPose(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gripperPoseRequest', 'DesiredGripperPose');
            obj.DesiredGripperPose = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.px_msgs.gripperPoseRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.px_msgs.gripperPoseRequest(strObj);
        end
    end
end
