
classdef ikinemResponse < ros.Message
    %ikinemResponse MATLAB implementation of px_msgs/ikinemResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'px_msgs/ikinemResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1271ba35eef0093eb929613318e34bb9' % The MD5 Checksum of the message definition
        PropertyList = { 'RobotConfiguration' } % List of non-constant message properties
        ROSPropertyList = { 'robotConfiguration' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.px_msgs.pxConfigVector' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        RobotConfiguration
    end
    methods
        function set.RobotConfiguration(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.px_msgs.pxConfigVector'};
            validateattributes(val, validClasses, validAttributes, 'ikinemResponse', 'RobotConfiguration')
            obj.RobotConfiguration = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.px_msgs.ikinemResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.px_msgs.ikinemResponse(strObj);
        end
    end
end
