
classdef pxConfig < ros.Message
    %pxConfig MATLAB implementation of px_msgs/pxConfig
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'px_msgs/pxConfig' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'a0b3cf724f5e56edf74eff88e607bd1b' % The MD5 Checksum of the message definition
        PropertyList = { 'Q1' 'Q2' 'Q3' 'Q4' 'Q5' } % List of non-constant message properties
        ROSPropertyList = { 'q1' 'q2' 'q3' 'q4' 'q5' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Q1
        Q2
        Q3
        Q4
        Q5
    end
    methods
        function set.Q1(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'pxConfig', 'Q1');
            obj.Q1 = double(val);
        end
        function set.Q2(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'pxConfig', 'Q2');
            obj.Q2 = double(val);
        end
        function set.Q3(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'pxConfig', 'Q3');
            obj.Q3 = double(val);
        end
        function set.Q4(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'pxConfig', 'Q4');
            obj.Q4 = double(val);
        end
        function set.Q5(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'pxConfig', 'Q5');
            obj.Q5 = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.px_msgs.pxConfig.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.px_msgs.pxConfig(strObj);
        end
    end
end
