
classdef pxIkinemRequest < ros.Message
    %pxIkinemRequest MATLAB implementation of px_msgs/pxIkinemRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'px_msgs/pxIkinemRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e7bb0ef028c744b081acdc57743b11d8' % The MD5 Checksum of the message definition
        PropertyList = { 'Position' } % List of non-constant message properties
        ROSPropertyList = { 'position' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Vector3' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Position
    end
    methods
        function set.Position(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'pxIkinemRequest', 'Position')
            obj.Position = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.px_msgs.pxIkinemRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.px_msgs.pxIkinemRequest(strObj);
        end
    end
end
