
classdef pxIkinemResponse < ros.Message
    %pxIkinemResponse MATLAB implementation of px_msgs/pxIkinemResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'px_msgs/pxIkinemResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '6c4d0db16d46ac55a24821cb779ffd22' % The MD5 Checksum of the message definition
        PropertyList = { 'Config' } % List of non-constant message properties
        ROSPropertyList = { 'config' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.px_msgs.pxConfig' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Config
    end
    methods
        function set.Config(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.px_msgs.pxConfig'};
            validateattributes(val, validClasses, validAttributes, 'pxIkinemResponse', 'Config')
            obj.Config = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.px_msgs.pxIkinemResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.px_msgs.pxIkinemResponse(strObj);
        end
    end
end
