// Generated by gencpp from file px_msgs/pedroPascal.msg
// DO NOT EDIT!


#ifndef PX_MSGS_MESSAGE_PEDROPASCAL_H
#define PX_MSGS_MESSAGE_PEDROPASCAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace px_msgs
{
template <class ContainerAllocator>
struct pedroPascal_
{
  typedef pedroPascal_<ContainerAllocator> Type;

  pedroPascal_()
    : positions()  {
    }
  pedroPascal_(const ContainerAllocator& _alloc)
    : positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::px_msgs::pedroPascal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px_msgs::pedroPascal_<ContainerAllocator> const> ConstPtr;

}; // struct pedroPascal_

typedef ::px_msgs::pedroPascal_<std::allocator<void> > pedroPascal;

typedef boost::shared_ptr< ::px_msgs::pedroPascal > pedroPascalPtr;
typedef boost::shared_ptr< ::px_msgs::pedroPascal const> pedroPascalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px_msgs::pedroPascal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px_msgs::pedroPascal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px_msgs::pedroPascal_<ContainerAllocator1> & lhs, const ::px_msgs::pedroPascal_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px_msgs::pedroPascal_<ContainerAllocator1> & lhs, const ::px_msgs::pedroPascal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px_msgs::pedroPascal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px_msgs::pedroPascal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px_msgs::pedroPascal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px_msgs::pedroPascal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px_msgs::pedroPascal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px_msgs::pedroPascal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px_msgs::pedroPascal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b12cb6666ed1af9d7c5102077c269d3";
  }

  static const char* value(const ::px_msgs::pedroPascal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b12cb6666ed1af9ULL;
  static const uint64_t static_value2 = 0xd7c5102077c269d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::px_msgs::pedroPascal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px_msgs/pedroPascal";
  }

  static const char* value(const ::px_msgs::pedroPascal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px_msgs::pedroPascal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3[] positions\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::px_msgs::pedroPascal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px_msgs::pedroPascal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pedroPascal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px_msgs::pedroPascal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px_msgs::pedroPascal_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX_MSGS_MESSAGE_PEDROPASCAL_H
