
classdef pedroPascal < ros.Message
    %pedroPascal MATLAB implementation of px_msgs/pedroPascal
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'px_msgs/pedroPascal' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1b12cb6666ed1af9d7c5102077c269d3' % The MD5 Checksum of the message definition
        PropertyList = { 'Positions' } % List of non-constant message properties
        ROSPropertyList = { 'positions' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Vector3' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Positions
    end
    methods
        function set.Positions(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.geometry_msgs.Vector3.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'pedroPascal', 'Positions')
            obj.Positions = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.px_msgs.pedroPascal.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.px_msgs.pedroPascal(strObj);
        end
    end
end
